[nfs]
172.31.23.119 ansible_ssh_user='ec2-user'

[webservers]
172.31.23.98 ansible_ssh_user='ec2-user'
172.31.18.94 ansible_ssh_user='ec2-user'

[db]
172.31.25.194 ansible_ssh_user='ec2-user' 

[lb]
172.31.17.134 ansible_ssh_user='ubuntu'