[nfs]
172.31.23.119

[webservers]
172.31.23.98
172.31.18.94

[db]
172.31.25.194

[lb]
172.31.17.134

# [deployment:children]
# db
# lb

# [deployment:vars]
# ansible_user=ec2-user
# ansible_python_interpreter=/usr/libexec/platform-python
# ansible_ssh_private_key_file=~/.ssh/id_rsa